/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AccordionVanillaImport } from './routes/accordion/vanilla'
import { Route as AccordionReactImport } from './routes/accordion/react'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AccordionVanillaRoute = AccordionVanillaImport.update({
  id: '/accordion/vanilla',
  path: '/accordion/vanilla',
  getParentRoute: () => rootRoute,
} as any)

const AccordionReactRoute = AccordionReactImport.update({
  id: '/accordion/react',
  path: '/accordion/react',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/accordion/react': {
      id: '/accordion/react'
      path: '/accordion/react'
      fullPath: '/accordion/react'
      preLoaderRoute: typeof AccordionReactImport
      parentRoute: typeof rootRoute
    }
    '/accordion/vanilla': {
      id: '/accordion/vanilla'
      path: '/accordion/vanilla'
      fullPath: '/accordion/vanilla'
      preLoaderRoute: typeof AccordionVanillaImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accordion/react': typeof AccordionReactRoute
  '/accordion/vanilla': typeof AccordionVanillaRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accordion/react': typeof AccordionReactRoute
  '/accordion/vanilla': typeof AccordionVanillaRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/accordion/react': typeof AccordionReactRoute
  '/accordion/vanilla': typeof AccordionVanillaRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accordion/react' | '/accordion/vanilla'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accordion/react' | '/accordion/vanilla'
  id: '__root__' | '/' | '/accordion/react' | '/accordion/vanilla'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccordionReactRoute: typeof AccordionReactRoute
  AccordionVanillaRoute: typeof AccordionVanillaRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccordionReactRoute: AccordionReactRoute,
  AccordionVanillaRoute: AccordionVanillaRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/accordion/react",
        "/accordion/vanilla"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/accordion/react": {
      "filePath": "accordion/react.tsx"
    },
    "/accordion/vanilla": {
      "filePath": "accordion/vanilla.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
